server:
  port: ${APP_PORT}
  servlet:
    context-path: ${BASE_PATH}

spring:
  application:
    name: ru-levelp-srv-person-profile
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  web:
    resources:
      add-mappings: false

springfox:
  documentation:
    auto-startup: false

logging:
  config: ${LOGGING_SETTINGS_PATH}
  level:
    root: ${APP_LOGLEVEL}
