version: '3.7'

services:

  person-profile-postgres:
    image: postgres:14.3
    container_name: person-profile-postgres
    hostname: person-profile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: person_profile
      POSTGRES_USER: person_profile
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_person_profile:/var/lib/postgres

  person-profile-liquibase:
    image: liquibase/liquibase:4.10
    container_name: person-profile-liquibase
    volumes:
      - ../src/main/resources/changelog/.:/liquibase/changelog
    command:
      --changeLogFile=changelog-master.yaml
      --driver=org.postgresql.Driver
      --url=jdbc:postgresql://person-profile-postgres:5432/person_profile
      --username=person_profile
      --password=password
      update
    depends_on:
      - person-profile-postgres

volumes:
  postgres_data_person_profile:
