version: '3.7'

services:

  person-profile-postgres:
    image: postgres:14.3
    container_name: person-profile-postgres
    hostname: person-profile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: person_profile
      POSTGRES_USER: person_profile
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_person_profile:/var/lib/postgres

volumes:
  postgres_data_person_profile:
